trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    inputs:
      versionSpec: '1.x'

  - script: yarn
    displayName: Install Dependencies

  - script: yarn compile
    displayName: Compile

  - script: yarn test
    displayName: Run Tests
