name: run-tests
on: push
permissions: {}
jobs:
  yarn-ubuntu:
    name: yarn-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      with:
        persist-credentials: false
    - name: Run yarn
      run: |
        yarn && yarn compile && yarn test
  yarn-windows:
    name: yarn-windows
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      with:
        persist-credentials: false
    - name: Run yarn
      run: |
        yarn && yarn compile && yarn test
