name: Unit Tests
on: [push, pull_request]
jobs:
  yarn:
    name: Yarn
    runs-on: [ubuntu-latest, windows-latest]
    steps:
    - name: Run yarn
      run: |
        yarn && yarn compile && yarn test
