name: Unit Tests
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - '*'
jobs:
  yarn:
    name: yarn-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Run yarn
      run: |
        yarn && yarn compile && yarn test
    name: yarn-windows
    runs-on: windows-latest
    steps:
    - name: Run yarn
      run: |
        yarn && yarn compile && yarn test
