name: Unit Tests
on: push
jobs:
  yarn-ubuntu:
    name: yarn-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Run yarn
      run: |
        yarn && yarn compile && yarn test
  yarn-windows:
    name: yarn-windows
    runs-on: windows-latest
    steps:
    - name: Run yarn
      run: |
        yarn && yarn compile && yarn test
